#!/bin/bash
echo "Enter target"
read target

echo "Enter referer"
read referer

echo "Enter count of visit"
read count_visit

echo "Enter count of thread"
read count_thread

echo "Enter deep"
read deep

echo "Enter the range in seconds. Example: (5-15)"
read sleep_range

count_visit=$(echo $count_visit / $count_thread | bc)

for((i=0; i<$count_thread; i++))
do
	./thread $count_visit $target $referer $deep $sleep_range &
done
exit 0