#!/bin/bash
count_visit=$1
target=$2
referer=$3
deep=$4
sleep_range=$5
# echo $count_visit
for((i=0; i<$count_visit; i++))
do
	proxy=$(shuf -n 1 files/proxy.txt)
	echo $proxy
	ua=$(shuf -n 1 files/user-agent.txt | base64 -w 0)
	resolution=$(shuf -n 1 files/resolution.txt)
	cookie=$(ls files/cookies | shuf -n 1)
	
	#--proxy=$proxy --cookies-path=$cookie
	./phantomjs --ignore-ssl-errors=true --web-security=false --proxy=$proxy --cookies-file=files/cookies/$cookie \
	new_visitor.js $target $referer $ua $deep $resolution $sleep_range
done
exit 0